//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeCapsuleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGES
    {
        public int MessageId { get; set; }
        public int UserId { get; set; }
        public string MessageText { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime LockedUntil { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ReceiverEmail { get; set; }
        public Nullable<bool> IsSent { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
